# Generated by Django 4.2 on 2023-10-18 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
    ]
