# Generated by Django 4.2 on 2023-10-18 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_remove_doctor_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='last_name',
        ),
    ]
