# Generated by Django 4.2.7 on 2023-11-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_rename_first_name_doctor_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recovered_Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleteing_user', models.TextField()),
                ('name', models.TextField()),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.TextField()),
                ('working_status', models.TextField()),
                ('profession', models.TextField()),
                ('country', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
